compressionLevel: mixed

enableGlobalCache: false

ignorePath: true

nodeLinker: pnp

npmAlwaysAuth: false

npmAuditRegistry: 'https://registry.npmjs.org'

npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.0.1.cjs
