nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs

npmAlwaysAuth: false

ignorePath: true

npmAuditRegistry: 'https://registry.npmjs.org'

npmRegistryServer: 'https://registry.npmjs.org'
